/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Actividad1;

import java.awt.Color;
import javax.script.ScriptEngine;
import javax.script.ScriptEngineManager;
import javax.script.ScriptException;


/**
 *
 * @author adrian
 */
public class Calculadora extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(Calculadora.class.getName());

    /**
     * Creates new form Calculadora
     */
    public Calculadora() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel4 = new javax.swing.JLabel();
        fondo = new javax.swing.JPanel();
        boton0 = new javax.swing.JButton();
        botonMas = new javax.swing.JButton();
        botonRes = new javax.swing.JButton();
        BotonBack = new javax.swing.JButton();
        Boton1 = new javax.swing.JButton();
        Boton2 = new javax.swing.JButton();
        Boton3 = new javax.swing.JButton();
        BotonDiv = new javax.swing.JButton();
        Boton4 = new javax.swing.JButton();
        Boton5 = new javax.swing.JButton();
        Boton6 = new javax.swing.JButton();
        BotonMul = new javax.swing.JButton();
        Boton7 = new javax.swing.JButton();
        Boton8 = new javax.swing.JButton();
        Boton9 = new javax.swing.JButton();
        BotonResul = new javax.swing.JButton();
        entrada = new javax.swing.JTextField();

        jLabel4.setFont(new java.awt.Font("Liberation Sans", 0, 36)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 0, 0));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("3");
        jLabel4.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        fondo.setBackground(new java.awt.Color(153, 153, 255));

        boton0.setBackground(new java.awt.Color(153, 153, 255));
        boton0.setFont(new java.awt.Font("Liberation Sans", 0, 48)); // NOI18N
        boton0.setForeground(new java.awt.Color(255, 255, 255));
        boton0.setText("0");
        boton0.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        boton0.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boton0ActionPerformed(evt);
            }
        });

        botonMas.setBackground(new java.awt.Color(153, 153, 255));
        botonMas.setFont(new java.awt.Font("Liberation Sans", 0, 48)); // NOI18N
        botonMas.setForeground(new java.awt.Color(255, 255, 255));
        botonMas.setText("+");
        botonMas.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        botonMas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonMasActionPerformed(evt);
            }
        });

        botonRes.setBackground(new java.awt.Color(153, 153, 255));
        botonRes.setFont(new java.awt.Font("Liberation Sans", 0, 48)); // NOI18N
        botonRes.setForeground(new java.awt.Color(255, 255, 255));
        botonRes.setText("-");
        botonRes.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        botonRes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonResActionPerformed(evt);
            }
        });

        BotonBack.setBackground(new java.awt.Color(153, 153, 255));
        BotonBack.setFont(new java.awt.Font("Liberation Sans", 0, 36)); // NOI18N
        BotonBack.setForeground(new java.awt.Color(255, 255, 255));
        BotonBack.setText("CE");
        BotonBack.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        BotonBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonBackActionPerformed(evt);
            }
        });

        Boton1.setBackground(new java.awt.Color(153, 153, 255));
        Boton1.setFont(new java.awt.Font("Liberation Sans", 0, 48)); // NOI18N
        Boton1.setForeground(new java.awt.Color(255, 255, 255));
        Boton1.setText("1");
        Boton1.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        Boton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Boton1ActionPerformed(evt);
            }
        });

        Boton2.setBackground(new java.awt.Color(153, 153, 255));
        Boton2.setFont(new java.awt.Font("Liberation Sans", 0, 48)); // NOI18N
        Boton2.setForeground(new java.awt.Color(255, 255, 255));
        Boton2.setText("2");
        Boton2.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        Boton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Boton2ActionPerformed(evt);
            }
        });

        Boton3.setBackground(new java.awt.Color(153, 153, 255));
        Boton3.setFont(new java.awt.Font("Liberation Sans", 0, 48)); // NOI18N
        Boton3.setForeground(new java.awt.Color(255, 255, 255));
        Boton3.setText("3");
        Boton3.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        Boton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Boton3ActionPerformed(evt);
            }
        });

        BotonDiv.setBackground(new java.awt.Color(153, 153, 255));
        BotonDiv.setFont(new java.awt.Font("Liberation Sans", 0, 48)); // NOI18N
        BotonDiv.setForeground(new java.awt.Color(255, 255, 255));
        BotonDiv.setText("/");
        BotonDiv.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        BotonDiv.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonDivActionPerformed(evt);
            }
        });

        Boton4.setBackground(new java.awt.Color(153, 153, 255));
        Boton4.setFont(new java.awt.Font("Liberation Sans", 0, 48)); // NOI18N
        Boton4.setForeground(new java.awt.Color(255, 255, 255));
        Boton4.setText("4");
        Boton4.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        Boton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Boton4ActionPerformed(evt);
            }
        });

        Boton5.setBackground(new java.awt.Color(153, 153, 255));
        Boton5.setFont(new java.awt.Font("Liberation Sans", 0, 48)); // NOI18N
        Boton5.setForeground(new java.awt.Color(255, 255, 255));
        Boton5.setText("5");
        Boton5.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        Boton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Boton5ActionPerformed(evt);
            }
        });

        Boton6.setBackground(new java.awt.Color(153, 153, 255));
        Boton6.setFont(new java.awt.Font("Liberation Sans", 0, 48)); // NOI18N
        Boton6.setForeground(new java.awt.Color(255, 255, 255));
        Boton6.setText("6");
        Boton6.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        Boton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Boton6ActionPerformed(evt);
            }
        });

        BotonMul.setBackground(new java.awt.Color(153, 153, 255));
        BotonMul.setFont(new java.awt.Font("Liberation Sans", 0, 48)); // NOI18N
        BotonMul.setForeground(new java.awt.Color(255, 255, 255));
        BotonMul.setText("*");
        BotonMul.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        BotonMul.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonMulActionPerformed(evt);
            }
        });

        Boton7.setBackground(new java.awt.Color(153, 153, 255));
        Boton7.setFont(new java.awt.Font("Liberation Sans", 0, 48)); // NOI18N
        Boton7.setForeground(new java.awt.Color(255, 255, 255));
        Boton7.setText("7");
        Boton7.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        Boton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Boton7ActionPerformed(evt);
            }
        });

        Boton8.setBackground(new java.awt.Color(153, 153, 255));
        Boton8.setFont(new java.awt.Font("Liberation Sans", 0, 48)); // NOI18N
        Boton8.setForeground(new java.awt.Color(255, 255, 255));
        Boton8.setText("8");
        Boton8.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        Boton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Boton8ActionPerformed(evt);
            }
        });

        Boton9.setBackground(new java.awt.Color(153, 153, 255));
        Boton9.setFont(new java.awt.Font("Liberation Sans", 0, 48)); // NOI18N
        Boton9.setForeground(new java.awt.Color(255, 255, 255));
        Boton9.setText("9");
        Boton9.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        Boton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Boton9ActionPerformed(evt);
            }
        });

        BotonResul.setBackground(new java.awt.Color(153, 153, 255));
        BotonResul.setFont(new java.awt.Font("Liberation Sans", 0, 48)); // NOI18N
        BotonResul.setForeground(new java.awt.Color(255, 255, 255));
        BotonResul.setText("=");
        BotonResul.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        BotonResul.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonResulActionPerformed(evt);
            }
        });

        entrada.setBackground(new java.awt.Color(204, 204, 255));
        entrada.setFont(new java.awt.Font("Liberation Sans", 0, 36)); // NOI18N
        entrada.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                entradaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout fondoLayout = new javax.swing.GroupLayout(fondo);
        fondo.setLayout(fondoLayout);
        fondoLayout.setHorizontalGroup(
            fondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(fondoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(fondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(entrada)
                    .addGroup(fondoLayout.createSequentialGroup()
                        .addGroup(fondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(fondoLayout.createSequentialGroup()
                                .addComponent(boton0, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(botonMas, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(botonRes, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(BotonBack, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(fondoLayout.createSequentialGroup()
                                .addComponent(Boton1, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(Boton2, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(Boton3, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(BotonDiv, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(fondoLayout.createSequentialGroup()
                                .addComponent(Boton4, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(Boton5, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(Boton6, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(BotonMul, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(fondoLayout.createSequentialGroup()
                                .addComponent(Boton7, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(Boton8, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(Boton9, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(BotonResul, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        fondoLayout.setVerticalGroup(
            fondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, fondoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(entrada, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(fondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Boton7, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Boton8, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Boton9, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BotonResul, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(fondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Boton4, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Boton5, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Boton6, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BotonMul, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(fondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Boton1, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Boton2, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BotonDiv, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Boton3, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(fondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(fondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(boton0, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(botonRes, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(botonMas, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(BotonBack, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(fondo, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(fondo, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void boton0ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boton0ActionPerformed
        entrada.setText(entrada.getText() + "0");
    }//GEN-LAST:event_boton0ActionPerformed

    private void botonResActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonResActionPerformed
        entrada.setText(entrada.getText() + "-");
    }//GEN-LAST:event_botonResActionPerformed

    private void botonMasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonMasActionPerformed
        entrada.setText(entrada.getText() + "+");
    }//GEN-LAST:event_botonMasActionPerformed

    private void BotonBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonBackActionPerformed
        entrada.setText("");
    }//GEN-LAST:event_BotonBackActionPerformed

    private void Boton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Boton1ActionPerformed
        entrada.setText(entrada.getText() + "1");
    }//GEN-LAST:event_Boton1ActionPerformed

    private void Boton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Boton2ActionPerformed
        entrada.setText(entrada.getText() + "2");
    }//GEN-LAST:event_Boton2ActionPerformed

    private void BotonDivActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonDivActionPerformed
        entrada.setText(entrada.getText() + "/");
    }//GEN-LAST:event_BotonDivActionPerformed

    private void Boton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Boton4ActionPerformed
        entrada.setText(entrada.getText() + "4");
    }//GEN-LAST:event_Boton4ActionPerformed

    private void Boton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Boton5ActionPerformed
        entrada.setText(entrada.getText() + "5");
    }//GEN-LAST:event_Boton5ActionPerformed

    private void Boton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Boton6ActionPerformed
        entrada.setText(entrada.getText() + "6");
    }//GEN-LAST:event_Boton6ActionPerformed

    private void BotonMulActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonMulActionPerformed
        entrada.setText(entrada.getText() + "*");
    }//GEN-LAST:event_BotonMulActionPerformed

    private void Boton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Boton7ActionPerformed
        entrada.setText(entrada.getText() + "7");
    }//GEN-LAST:event_Boton7ActionPerformed

    private void Boton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Boton8ActionPerformed
        entrada.setText(entrada.getText() + "8");
    }//GEN-LAST:event_Boton8ActionPerformed

    private void Boton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Boton9ActionPerformed
        entrada.setText(entrada.getText() + "9");
    }//GEN-LAST:event_Boton9ActionPerformed

    private void BotonResulActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonResulActionPerformed
        String expresion = entrada.getText().trim();

        if (expresion.isEmpty()) {
            return;
        }

        char ultimo = expresion.charAt(expresion.length() - 1);
        if ("+-*/".indexOf(ultimo) >= 0) {
            entrada.setText("Error");
            return;
        }

        if (expresion.contains("/0")) {
            entrada.setText("División por Cero");
            return;
        }

        try {
            long resultado = evaluarExpresionEntera(expresion);

            // Muestra el resultado como un entero largo (long)
            entrada.setText(String.valueOf(resultado));

        } catch (ArithmeticException ae) {
            // Captura errores de división por cero
            entrada.setText(ae.getMessage());
        }
        catch (Exception e) {
            // En caso de cualquier otro error (sintaxis, etc.)
            entrada.setText("Error de Sintaxis");
        }
    }//GEN-LAST:event_BotonResulActionPerformed

    private void Boton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Boton3ActionPerformed
        entrada.setText(entrada.getText() + "3");
    }//GEN-LAST:event_Boton3ActionPerformed

    private void entradaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_entradaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_entradaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new Calculadora().setVisible(true));
    }
    
 

    private long evaluarExpresionEntera(String expresion) {
        java.util.Stack<Long> numeros = new java.util.Stack<>(); // Cambiado a Long
        java.util.Stack<Character> operadores = new java.util.Stack<>();

        for (int i = 0; i < expresion.length(); i++) {
            char c = expresion.charAt(i);

            if (c == ' ') continue;

            if (Character.isDigit(c)) {
                StringBuilder num = new StringBuilder();
                while (i < expresion.length() && Character.isDigit(expresion.charAt(i))) {
                    num.append(expresion.charAt(i));
                    i++;
                }
                i--;
                // Usamos Long.parseLong para obtener el valor entero
                numeros.push(Long.parseLong(num.toString()));
            } else if ("+-*/".indexOf(c) >= 0) {
                while (!operadores.isEmpty() && precedencia(operadores.peek()) >= precedencia(c)) {
                    if (numeros.size() < 2) throw new IllegalArgumentException("Expresión inválida");
                    long b = numeros.pop(); // Pop de long
                    long a = numeros.pop(); // Pop de long
                    char op = operadores.pop();
                    numeros.push(operarEntero(a, b, op)); // Llama al método entero
                }
                operadores.push(c);
            }
        }

        while (!operadores.isEmpty()) {
            if (numeros.size() < 2) throw new IllegalArgumentException("Expresión inválida");
            long b = numeros.pop(); // Pop de long
            long a = numeros.pop(); // Pop de long
            char op = operadores.pop();
            numeros.push(operarEntero(a, b, op)); // Llama al método entero
        }

        if (numeros.size() != 1) throw new IllegalArgumentException("Expresión inválida");
        return numeros.pop();
    }

    private int precedencia(char op) {
        if (op == '+' || op == '-') return 1;
        if (op == '*' || op == '/') return 2;
        return 0;
    }

    private long operarEntero(long a, long b, char op) {
        switch (op) {
            case '+': return a + b;
            case '-': return a - b;
            case '*': return a * b;
            case '/': 
                if (b == 0) throw new ArithmeticException("División por Cero");
                // La división de long en Java es automáticamente división entera (descarta el resto)
                return a / b;
        }
        return 0;
    }

    private double operar(double a, double b, char op) {
        switch (op) {
            case '+': return a + b;
            case '-': return a - b;
            case '*': return a * b;
            case '/': return a / b;
        }
        return 0;
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Boton1;
    private javax.swing.JButton Boton2;
    private javax.swing.JButton Boton3;
    private javax.swing.JButton Boton4;
    private javax.swing.JButton Boton5;
    private javax.swing.JButton Boton6;
    private javax.swing.JButton Boton7;
    private javax.swing.JButton Boton8;
    private javax.swing.JButton Boton9;
    private javax.swing.JButton BotonBack;
    private javax.swing.JButton BotonDiv;
    private javax.swing.JButton BotonMul;
    private javax.swing.JButton BotonResul;
    private javax.swing.JButton boton0;
    private javax.swing.JButton botonMas;
    private javax.swing.JButton botonRes;
    private javax.swing.JTextField entrada;
    private javax.swing.JPanel fondo;
    private javax.swing.JLabel jLabel4;
    // End of variables declaration//GEN-END:variables
}
